<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<!DOCTYPE document [
  <!ENTITY project SYSTEM "project.xml">

  <!-- DTD is used to validate changelog structure at build time. BZ 64931. -->

  <!ELEMENT document (project?, properties, body)>
  <!ATTLIST document url CDATA #REQUIRED>

  <!-- body and title are used both in project.xml and in this document -->
  <!ELEMENT body ANY>
  <!ELEMENT title (#PCDATA)>

  <!-- Elements of project.xml -->
  <!ELEMENT project (title, logo, body)>
  <!ATTLIST project name CDATA #REQUIRED>
  <!ATTLIST project href CDATA #REQUIRED>

  <!ELEMENT logo (#PCDATA)>
  <!ATTLIST logo href CDATA #REQUIRED>

  <!ELEMENT menu (item+)>
  <!ATTLIST menu name CDATA #REQUIRED>

  <!ELEMENT item EMPTY>
  <!ATTLIST item name CDATA #REQUIRED>
  <!ATTLIST item href CDATA #REQUIRED>

  <!-- Elements of this document -->
  <!ELEMENT properties (author*, title, no-comments) >
  <!ELEMENT author (#PCDATA)>
  <!ATTLIST author email CDATA #IMPLIED>
  <!ELEMENT no-comments EMPTY>

  <!ELEMENT section (subsection)*>
  <!ATTLIST section name CDATA #REQUIRED>
  <!ATTLIST section rtext CDATA #IMPLIED>

  <!ELEMENT subsection (changelog+)>
  <!ATTLIST subsection name CDATA #REQUIRED>

  <!ELEMENT changelog (add|update|fix|scode|docs|design)*>
  <!ELEMENT add ANY>
  <!ELEMENT update ANY>
  <!ELEMENT fix ANY>
  <!ELEMENT scode ANY>
  <!ELEMENT docs ANY>
  <!ELEMENT design ANY>

  <!ELEMENT bug (#PCDATA)>
  <!ELEMENT rev (#PCDATA)>
  <!ELEMENT pr (#PCDATA)>

  <!-- Random HTML markup tags. Add more here as needed. -->
  <!ELEMENT a (#PCDATA)>
  <!ATTLIST a href CDATA #REQUIRED>
  <!ATTLIST a rel CDATA #IMPLIED>

  <!ELEMENT b (#PCDATA)>
  <!ELEMENT code (#PCDATA)>
  <!ELEMENT em (#PCDATA)>
  <!ELEMENT strong (#PCDATA)>
  <!ELEMENT tt (#PCDATA)>
]>
<?xml-stylesheet type="text/xsl" href="tomcat-docs.xsl"?>
<document url="changelog.html">

  &project;

  <properties>
    <title>Changelog</title>
    <no-comments />
  </properties>

<body>
<!--
  For guidance on writing changelog entries, see the "Changelog Entries"
  section in CONTRIBUTING.md.

  Subsection ordering:
  General, Catalina, Coyote, Jasper, Cluster, WebSocket, Web applications,
  Extras, Tribes, jdbc-pool, Other

  Item Ordering:

  Fixes having an issue number are sorted by their number, ascending.

  There is no ordering by add/update/fix/scode/docs/design.

  Other fixed issues are added to the end of the list, chronologically.
  They eventually become mixed with the numbered issues (i.e., numbered
  issues do not "pop up" wrt. others).
-->
<section name="Tomcat 11.0.25 (markt)" rtext="in development">
  <subsection name="Catalina">
    <changelog>
      <fix>
        Ensure that a <code>login-config</code> conflict when merging web.xml
        fragments triggers a deployment failure. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Coyote">
    <changelog>
      <update>
        Add utility AutoCloseable URLConnection wrapper, and use it to cleanup
        existing code patterns. (remm/markt)
      </update>
    </changelog>
  </subsection>
  <subsection name="Cluster">
    <changelog>
      <add>
        Change the default <code>encryptionAlgorithm</code> for the
        <code>EncryptInterceptor</code> to <code>AES/GCM/NoPadding</code>. This
        is a breaking change for the <code>EncryptInterceptor</code>. (markt)
      </add>
      <add>
        Expand the documentation for the <code>EncryptInterceptor</code> to be
        more explicit regarding the security weaknesses of some supported
        algorithms. Also explicitly state that the replay protection is only
        effective for non-malleable algorithms. (markt)
      </add>
      <add>
        Expand the Javadoc for the <code>DNSMembershipProvider</code> in
        particular explaining its behaviour and providing configuration advice
        if control more over cluster membership is required. (markt)
      </add>
    </changelog>
  </subsection>
</section>
<section name="Tomcat 11.0.24 (markt)" rtext="2026-07-08">
  <subsection name="Catalina">
    <changelog>
      <fix>
        Avoid a race condition with concurrent lookups for a singleton JNDI
        resource. (markt)
      </fix>
      <fix>
        Improve the performance of range validation for the default servlet.
        (markt)
      </fix>
      <fix>
        Avoid NPE in RewriteValve. (markt)
      </fix>
      <fix>
        <bug>70127</bug>: Fix use of Bootstrap through reflection by restoring
        the public constructor. Use through scripts was not affected. (remm)
      </fix>
      <fix>
        Restore ability to extend many element classes from
        <code>AbstractAccessLogValve</code>. (remm)
      </fix>
      <fix>
        Align DIGEST authentication with RFC 7616 and require clients to provide
        a valid <code>qop</code> parameter. (markt)
      </fix>
      <fix>
        Use <code>Files</code> API to create temporary docBase when
        <code>antiLockingDocBase</code> is enabled. (markt)
      </fix>
      <fix>
        Improve validation of configuration when <code>DataSourceRealm</code>
        starts. (remm)
      </fix>
      <fix>
        <code>JAASRealm</code> should do a logout if login does not fail outright but
        does not produce a Principal. (remm)
      </fix>
      <fix>
        Various edge cases for SSI substitutions, quoting and escaping. (remm)
      </fix>
      <fix>
        Fix unintentional conversion of literal <code>+</code> to a space during
        rule processing in the <code>RewriteValve</code>. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Coyote">
    <changelog>
      <fix>
        Avoid a potential JVM crash if a suitable version of Tomcat Native is
        not available when the connector is explicitly configured to use Tomcat
        Native with OpenSSL for TLS. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Jasper">
    <changelog>
      <fix>
        <bug>70120</bug>: The fix for <bug>69399</bug> (itself a fix for a
        regression in the fix for <bug>69333</bug>) was incomplete and tags that
        threw exceptions in <code>doStartTag()</code> and
        <code>doEndTag()</code> were incorrectly re-used. This fix prevents tags
        from being re-used if such an exception occurs. (markt)
      </fix>
      <add>
        Add support for specifying Java 28 (with the value <code>28</code>) as
        the compiler source and/or compiler target for JSP compilation. If used
        with an Eclipse JDT compiler version that does not support these values,
        a warning will be logged and the default will be used.
        (markt)
      </add>
    </changelog>
  </subsection>
  <subsection name="WebSocket">
    <changelog>
      <fix>
        <bug>70126</bug>: Fix WebSocket extension permessage-deflate so that it
        does not drop bytes if a compressed message inflates to more than the
        available buffer. Fix written by GPT-5.5. Test case written by Hironori
        Ichimiya. (markt)
      </fix>
      <fix>
        Optimise WebSocket client processing of server responses during
        WebSocket HTTP upgrade process. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Other">
    <changelog>
      <update>
        Update to the Eclipse JDT compiler 4.40. (markt)
      </update>
      <update>
        Update Byte Buddy to 1.18.9. (markt)
      </update>
      <update>
        Update UnboundID to 7.0.5. (markt)
      </update>
      <update>
        Update JaCoCo to 0.8.15. (markt)
      </update>
      <update>
        Update BND to 7.3.0. (markt)
      </update>
      <add>
        Improvements to French translations. (remm)
      </add>
      <add>
        Improvements to Japanese translations provided by tak7iji. (markt)
      </add>
    </changelog>
  </subsection>
</section>
<section name="Tomcat 11.0.23 (markt)" rtext="2026-06-22">
  <subsection name="Catalina">
    <changelog>
      <add>
        Add support for literal <code>'%'</code> characters in access log
        output. Based on pull request <pr>1002</pr> by Fabian Hahn. (markt)
      </add>
      <fix>
        Lower the log level to debug when OpenSSL initialization fails in
        <code>OpenSSLLifecycleListener</code> to avoid stack traces
        when <code>libssl.so</code> is not present and to align the behavior
        of the <code>isAvailable()</code> check with the
        <code>AprLifecycleListener</code> and gracefully fail when natives
        are not present. (csutherl)
      </fix>
      <fix>
        <bug>70038</bug>: <code>Cookie.clone()</code> should also clone the
        internal attribute map. (markt)
      </fix>
      <scode>
        Remove unnecessary code from the SSI processing engine that was
        duplicating some of the normalisation checks. (markt)
      </scode>
      <fix>
        Cleaner handling of invalid SPNEGO tokens. (remm)
      </fix>
      <fix>
        Avoid some NPEs in the Connector class on an uninitialize protocol.
        (remm)
      </fix>
      <fix>
        Incorrect session average life calculation. (remm)
      </fix>
      <fix>
        Improve robustness on using <code>Pipeline.setBasic</code> on a running
        pipeline. (remm)
      </fix>
      <fix>
        Avoid any init parameter updates when conflicts are found for filters,
        similar to what is done for servlets, as required by the servlet
        specification. (remm)
      </fix>
      <fix>
        Fix container event cleanups in some edge cases. (remm)
      </fix>
      <fix>
        Check for last-modified header in <code>ExpiresFilter</code> when a
        servlet uses <code>addDateHeader</code> to avoid wrongly considering
        it has been set. (remm)
      </fix>
      <fix>
        Fix hour unit used by <code>ExpiresFilter</code>. (remm)
      </fix>
      <fix>
        Remove exception swallowing in <code>DataSourceStore</code> to align
        it with <code>FileStore</code> and avoid session loss on errors. (remm)
      </fix>
      <fix>
        Add support for single-quote escaped literal as well as quoted literals
        in <code>DateFormatCache</code>. (schultz)
      </fix>
      <fix>
        On JAAS logout, clear out role principals on the subject that were
        added on commit, as recommended by the JAAS specification. (remm)
      </fix>
      <fix>
        <code>MemoryRealm</code> should not add a dummy role when none is
        specified in the configuration. (remm)
      </fix>
      <fix>
        <code>DataSourceUserDatabase</code> should return a null principal on
        a non existing user. (remm)
      </fix>
      <fix>
        Fix shared lock expiration in WebDAV. (remm)
      </fix>
      <fix>
        Inaccurate session exipration statistics when using the persistent
        manager. (remm)
      </fix>
      <fix>
        Skip BOM when serving files with UTF-32 encoding. (remm)
      </fix>
      <fix>
        Mixup of WrapperListener and WrapperLifecycle elements in storeconfig.
        (remm)
      </fix>
      <fix>
        Incorrect processing of modified users in
        <code>DataSourceUserDatabase</code>. (remm)
      </fix>
      <update>
        Clarify behavior in the <code>UserDatabase</code> for user, role and
        group creation that it does not immediately override existing elements.
        Removal (or update) needs to be used instead. (remm)
      </update>
      <fix>
        <bug>70049</bug>: Align the web application class loader with parent
        class loaders and swallow any errors caused by invalid paths when
        looking up resources and behave as if the resources were not found in
        that case. (markt)
      </fix>
      <fix>
        Improve validation of <code>Range</code> and <code>Content-Range</code>
        parsers so invalid ranges trigger a <code>4xx</code> response rather
        than a <code>500</code> response. Pull request <pr>1012</pr> provided by
        Sahana Surendra Bogar. (markt)
      </fix>
      <fix>
        Fix connection leak in <code>ProxyErrorReportValve</code>. (remm)
      </fix>
      <fix>
        When using the <code>RewriteValve</code>, <code>%{SSL:HTTPS}</code> now
        returns <code>on</code> or <code>off</code> rather than
        <code>true</code> or <code>false</code> to align with httpd. (markt)
      </fix>
      <fix>
        Reset the encoding used for query string parameters between requests in
        case an application changed the encoding in a previous request. (markt)
      </fix>
      <fix>
        When encoding URLs with the <code>CsrfPreventionFilter</code>, don't add
        the nonce to URLs that are known not to require it. (markt)
      </fix>
      <fix>
        Fix SSO cookie partitioned configuration. (remm)
      </fix>
      <fix>
        Fix <code>CombinedRealm</code> <code>isAvailable</code>, it allows
        authentication if at least one sub realm is available. (remm)
      </fix>
      <fix>
        <bug>70048</bug>: Correctly handle asynchronous requests in
        <code>PersistentValve</code>. (markt)
      </fix>
      <fix>
        Improve the detection of cross-context dispatches when using a
        <code>RequestDispatcher</code>. (markt)
      </fix>
      <fix>
        Fix various instances of double decoding of URL patterns configured
        either programmatically or in web.xml. (remm/markt)
      </fix>
      <fix>
        Align the rewrite conditions <code>ornext</code> flag processing with
        mod_rewrite, which follows a purely sequential evaluation strategy.
        (remm)
      </fix>
      <fix>
        Update default web.xml version to match supported Servlet specification
        version. (markt)
      </fix>
      <fix>
        Change the default for the <code>useRedirect</code> attribute of the
        <code>ProxyErrorReportValve</code> from <code>true</code> to
        <code>false</code>. (markt)
      </fix>
      <add>
        Add support for the <code>showReport</code> attribute in
        <code>JsonErrorReportValve</code> and
        <code>ProxyErrorReportValve</code>. When set to <code>false</code>,
        detailed error information (message, description, stack trace) is
        suppressed from error responses. (dsoumis)
      </add>
      <fix>
        Avoid a <code>NoClassDefFoundError</code> at startup when
        <code>catalina-tribes.jar</code> is removed but
        <code>catalina-ha.jar</code> is present and the
        <code>Cluster</code> element is enabled in
        <code>server.xml</code>. Cluster digester rules are now fully
        conditional on both JARs being available. (dsoumis)
      </fix>
      <fix>
        Fix a potential deadlock when copying resources using WebDAV. (markt)
      </fix>
      <fix>
        Add <code>jakarta.</code>, <code>org.apache.catalina.</code> and
        <code>org.apache.tomcat.</code>to the list of reserved prefixes for SSI
        variables and request attributes. (markt)
      </fix>
      <fix>
        Missing URL decoding when processing <code>addMapping</code> on a
        Servlet registration. (remm)
      </fix>
      <fix>
        The <code>Timeout</code> WebDAV header allows comma separated values
        (according to the examples in the RFC). Use the first acceptable value.
        (remm)
      </fix>
      <fix>
        Fix various issues when logging the effective web.xml for a web
        application. Empty sections are no longer logged. Special roles and
        empty authorisation constraints are included. All session cookie
        attributes are included. (markt)
      </fix>
      <fix>
        Expand the write lock for the save process in the
        <code>MemoryUserDatabase</code> to avoid concurrency issues with the
        file save operations. (markt)
      </fix>
      <fix>
        Ensure atomic session persistence in <code>FileStore</code>. Based on
        pull request <pr>1016</pr> by sahvx655-wq. (markt)
      </fix>
      <fix>
        Do not ignore methods configured on security constraints that map to the
        default servlet. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Coyote">
    <changelog>
      <add>
        Log a suitable warning if an encrypted PEM file is detected using an
        insecure form for encryption. (markt)
      </add>
      <fix>
        If TLS groups have been configured, use the configured groups rather
        than using OpenSSL's default TLS groups when using Tomcat Native with
        OpenSSL based connectors. (markt)
      </fix>
      <fix>
        For HTTP/2, ensure that any in progress request body reads are cancelled
        if the container resets the associated stream. This prevents delays
        waiting for reads to time out when it is known that no more data will be
        received. (markt)
      </fix>
      <fix>
        Ensure that malformed HTTP/2 messages that should trigger a stream reset
        do so, rather than triggered a connection close. (markt)
      </fix>
      <fix>
        Improve enforcement of header trailer allow list for HTTP/2. (remm)
      </fix>
      <fix>
        <bug>70050</bug>: Avoid NPE when no header frame is processed in HTTP/2,
        following refactor clean-up of header buffer. (remm)
      </fix>
      <fix>
        Properly use <code>pollerThreadPriority</code> for the NIO poller
        thread. (remm)
      </fix>
      <fix>
        Fix <code>MessageByte.equals</code> if called on a null MB. (remm)
      </fix>
      <fix>
        Call the delegate key manager in JSSE to retrieve the server key.
        (remm)
      </fix>
      <fix>
        Avoid overflow scenarios in Asn1Parser. (remm)
      </fix>
      <fix>
        <bug>70091</bug>: Add a new attribute, <code>allowSchemeMismatch</code>
        to <code>Http2Protocol</code> that allows the consistency check for the
        scheme provided by the user agent to be bypassed. (markt)
      </fix>
      <fix>
        <code>isTrailerFieldsReady</code> was always returning
        <code>true</code>. (remm)
      </fix>
      <fix>
        Align OpenSSL/Panama TLS implementation with other implementations and
        throw an exception if there is an error loading the provided CRL(s).
        (markt)
      </fix>
      <fix>
        Parsing of OpenSSL format cipher expressions incorrectly stopped if
        <code>@STRENGTH</code> was encountered, ignoring any subsequent
        expressions. (markt)
      </fix>
      <fix>
        Handle the case where the HTTP/2 payload length is insufficient for the
        mandatory data required by the flags set in the header. (markt)
      </fix>
      <fix>
        <bug>70102</bug>: Correct expected size of ticket keys when calling
        <code>setSessionTicketKeys</code> with an FFM connector. (markt)
      </fix>
      <fix>
        <bug>69988</bug>: Fix post handshake authentication for TLS 1.3. It was
        broken by a breaking change in OpenSSL between 1.1.1 and 3.0.0. (markt)
      </fix>
      <fix>
        When processing an OpenSSL cipher specification, fully align the order
        of the resulting ciphers with the order produced by OpenSSL. (markt)
      </fix>
      <add>
        Add support for Brainpool TLS groups. Patch provided by YStankov.
        (schultz)
      </add>
      <update>
        Update both the minimum and recommended version for Tomcat Native 2.x to
        2.0.15. (markt)
      </update>
      <update>
        Update the minimum version for Tomcat Native 1.x to 1.3.8. (markt)
      </update>
    </changelog>
  </subsection>
  <subsection name="Jasper">
    <changelog>
      <fix>
        Fix possible EL argument mismatch when it was set to null. (remm)
      </fix>
      <fix>
        Fix thread safety of <code>TagPluginManager</code>. (remm)
      </fix>
      <fix>
        Correctly use flush on JSP include. (remm)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Cluster">
    <changelog>
      <fix>
        Expand wording and increase visibility of log message when cloud
        membership is configured without a trust store as all certificates will
        be trusted in this configuration. (markt)
      </fix>
      <fix>
        Ensure listeners are correctly added and removed when configuring the
        channel coordinator. (markt)
      </fix>
      <fix>
        Fix some concurrency issues in <code>FragmentationInterceptor</code>.
        (markt)
      </fix>
      <fix>
        Fix some concurrency issues in <code>OrderInterceptor</code>.
        (markt)
      </fix>
      <fix>
        Fix some concurrency issues in <code>TwoPhaseCommitInterceptor</code>.
        (markt)
      </fix>
      <fix>
        Fix concurrency issues generating MD5 digests in the
        <code>CloudMembershipProvider</code> implementations. (markt)
      </fix>
      <add>
        Add replay protection to the <code>EncryptInterceptor</code>. This is a
        breaking change for the <code>EncryptInterceptor</code>. (markt)
      </add>
    </changelog>
  </subsection>
  <subsection name="WebSocket">
    <changelog>
      <fix>
        Incorrect <code>Future.isDone()</code> return by
        <code>AsyncChannelWrapperSecure</code>. (remm)
      </fix>
      <fix>
        Trigger standard WebSocket error handling if a call to
        <code>Endpoint.onOpen()</code> fails for a programmatic endpoint.
        (markt)
      </fix>
      <fix>
        <bug>70110</bug>: Fix memory leak if a call to
        <code>Endpoint.onOpen()</code> fails for a programmatic endpoint. Test
        case provided by uabdur. (markt)
      </fix>
      <fix>
        If a client presents invalid parameters when negotiating a WebSocket
        extension, decline the negotiation offer that includes the invalid
        parameters rather than failing the connection. Pull request
        <pr>1019</pr> provided by sahvx655-wq. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Web applications">
    <changelog>
      <add>
        Manager: Add checks to ensure that any uploaded files are uploaded to
        the expected location. (markt)
      </add>
      <add>
        Manager: Add checks to ensure that the requested context path for a
        deployed WAR, directory or descriptor file is valid. (markt)
      </add>
      <add>
        Documentation: Expand the description of some of the attributes of the
        <code>CrawlerSessionManagerValve</code>. (markt)
      </add>
      <fix>
        Documentation: Clearer description and correct documented default for
        <code>ocspSoftFail</code>. (markt)
      </fix>
      <fix>
        Fix double escaping in the context names for the JSON mode of the
        manager servlet. (remm)
      </fix>
      <fix>
        Manager: Ensure automatic deployment does not trigger an undeployment
        during a Manager triggered web application reload. (markt)
      </fix>
      <fix>
        Documentation: Provide better documentation for the <code>scheme</code>
        and <code>secure</code> attributes of a Connector. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Other">
    <changelog>
      <fix>
        Use per connection authenticator when executing an Ant task. (remm/markt)
      </fix>
      <update>
        Update Commons Daemon to 1.6.1. (markt)
      </update>
      <fix>
        Prevent duplicate log messages when clustering JARs are not present on
        startup. (csutherl)
      </fix>
      <update>
        Improvements to French translations. (remm)
      </update>
      <update>
        Improvements to Japanese translations provided by tak7iji. (markt)
      </update>
      <update>
        Update the packaged version of the Tomcat Migration Tool for Jakarta EE
        to 1.0.12. (markt)
      </update>
      <update>
        Update Tomcat Native to 2.0.15. (markt)
      </update>
    </changelog>
  </subsection>
</section>
<section name="Tomcat 11.0.22 (markt)" rtext="2026-05-05">
  <subsection name="Catalina">
    <changelog>
      <add>
        Enhance <code>version.sh</code> and <code>version.bat</code> to display
        APR, Tomcat Native, and OpenSSL version information (both APR and FFM
        implementations), along with version compatibility warnings and
        third-party library version information. (csutherl)
      </add>
    </changelog>
  </subsection>
  <subsection name="Coyote">
    <changelog>
      <fix>
        Avoid various edge cases if <code>Content-Length</code> is set via
        <code>setHeader(String,String)</code> or
        <code>addHeader(String,String)</code> with an invalid value by always
        clearing the previous value whether the new value is valid or not and
        ignoring any invalid new value. (markt)
      </fix>
      <scode>
        Refactor the calculation of the real index in the HPACK dynamic header
        table implementation to reduce code duplication. (markt)
      </scode>
      <fix>
        Fix various minor issues with some HTTP/2 stream error messages for
        HTTP/2. (markt)
      </fix>
      <fix>
        Consistently reject URIs containing <code>NULL</code> bytes when
        normalizing. (markt)
      </fix>
      <fix>
        Fix a few minor memory leaks on error paths reading TLS keys and
        certificates when using FFM. (markt)
      </fix>
      <fix>
        Refactor clean-up after HTTP/2 headers have been processed to aid GC
        after a stream reset. (markt)
      </fix>
      <fix>
        Align HTTP/2 trailer fields with HTTP/1.1 and filter out any fields
        not permitted in trailers. (markt)
      </fix>
      <fix>
        Free private keys after use in FFM based connector configuration.
        (markt)
      </fix>
      <fix>
        Correct an unlikely edge-case parsing bug in the HTTP/2 HPACK header
        decoding that could result in a valid header triggering an unexpected
        connection close. (markt)
      </fix>
      <fix>
        Refactor HTTP/2 HPACK encoding so header field names are only converted
        to lower case once during the encoding process. (markt)
      </fix>
      <fix>
        Refactor HTTP/2 header field validation so it occurs earlier. Extend
        validation to check for disallowed characters as well as upper case
        characters. (markt)
      </fix>
      <fix>
        Add TLS 1.3 groups added in OpenSSL 4.0. (remm)
      </fix>
      <fix>
        Add validation that the HTTP/2 <code>:scheme</code> pseudo-header is
        consistent with the use (or not) of TLS. (markt)
      </fix>
      <fix>
        Correct the  validation of pseudo headers and CONNECT requests to align
        Tomcat's behaviour with RFC 9113, section 8.5. (markt)
      </fix>
      <fix>
        Fix a potential integer overflow when allocating capacity from a
        connection level window update to individual HTTP/2 streams. Based on
        <pr>996</pr> by Mike Tingey Jr. (markt)
      </fix>
      <fix>
        Switch AJP secret comparison to a constant time algorithm. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="WebSocket">
    <changelog>
      <fix>
        Fix the initial connection to a WebSocket end point where the connection
        is made via a proxy that requires DIGEST authentication. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Other">
    <changelog>
      <fix>
        <bug>69993</bug>: Update the URL to the CDDL 1.0 license. (markt)
      </fix>
      <add>
        Add warning when OpenSSL binary is not found. (csutherl)
      </add>
      <add>
        Add check for Tomcat Native library, and log warning when it's not found
        to make it easier to see when it's not used by the suite. (csutherl)
      </add>
      <update>
        Update Byte Buddy to 1.18.8. (markt)
      </update>
      <update>
        Update Bouncy Castle to 1.84. (markt)
      </update>
      <update>
        Improvements to French translations. (remm)
      </update>
      <update>
        Improvements to Japanese translations provided by tak7iji. (markt)
      </update>
    </changelog>
  </subsection>
</section>
<section name="Tomcat 11.0.21 (markt)" rtext="2026-04-04">
  <subsection name="Catalina">
    <changelog>
      <fix>
        Add escaping for URI and query string in the access log. (markt)
      </fix>
    </changelog>
  </subsection>
  <subsection name="Coyote">
    <changelog>
      <fix>
        Fix an HTTP/2 header frame parsing bug that could result in a connection
        being closed without a <code>GOAWAY</code> frame if an invalid
        <code>HEADERS</code> frame was received. (markt)
      </fix>
      <fix>
        <bug>69982</bug>: Fix a bug in the non-blocking flushing code for
        NIO+TLS that meant that a response may not be fully written until the
        connection is closed. Pull request <pr>966</pr> provided by Phil Clay.
        (markt)
      </fix>
      <fix>
        Ensure the HTTP/2 request header read buffer is reset (including
        restoration to default size) after a stream reset. (markt)
      </fix>
      <add>